### ISSUE TITLE
Connection issues with 1.4.4

### ISSUE THREAD

**Issue by phit** [yariplus/nodebb-plugin-minecraft-integration#103]
Not sure what changed, upgraded NodeBB from 1.4.0 to 1.4.4

```
28.02 05:11:40 [Server] EventThread/INFO [nodebbintegration]: Error connecting to the forum.
28.02 05:11:40 [Server] EventThread/INFO [nodebbintegration]: io.socket.engineio.client.EngineIOException: xhr poll error
```

**Comment by phit** [comment]
nvm restarted the forum again and now it works, no clue what happened

**Comment by phit** [comment]
turns out it only works when nodebb is running in dev mode?!
maybe related? https://github.com/NodeBB/NodeBB/issues/5472

**Comment by phit** [comment]
so yeah, it's related to the issue above.. since I have no idea what origin the minecraft server is, I added this to my nodebb config.json
`    "socket.io": {
        "origins": "*:*"
    }`

**Comment by yariplus** [comment]
Wow. That is something. Maybe there's some way I can just add the server ip to origins at runtime.

**Comment by phit** [comment]
I worked on this a bit [here](https://github.com/phit/minecraft-nodebb-integration/blob/2d104f54c9218516bfb48ee01e27512160a72767/common/src/main/java/com/radiofreederp/nodebbintegration/socketio/SocketIOClient.java#L182), trying to set the origin header properly. Doesn't seem to work, connection still fails with the same error 😞 . Even added some debug, and the header is definitely set in code, not sure if socketio ever uses it though.

```
[Server] EventThread/INFO [nodebbintegration]: Error connecting to the forum.
[Server] EventThread/INFO [nodebbintegration]: io.socket.engineio.client.EngineIOException: xhr poll error
[Server] EventThread/INFO [nodebbintegration]: urlvar: https://forums.stonebound.net/
[Server] EventThread/INFO [nodebbintegration]: headers: {Cookie=[express.sid=COOKIEHERE; Path=/; Expires=Thu, 23 Mar 2017 22:27:08 GMT; HttpOnly; Secure], Origin=[https://forums.stonebound.net]}
```

Then I found [this issue](https://github.com/socketio/socket.io-client-java/issues/338), so it might be not my fault

**Comment by yariplus** [comment]
That is concerning. Thanks for trying to debug it. I should have time to investigate on Saturday.

Is working fully by just setting the origins to `*:*` on nbb?

**Comment by phit** [comment]
Yep, that's working fine. So don't worry the workaround is fine for now, after running for years without that "extra security" I think it wouldn't be to horrible if a fix for this had to wait..

**Comment by yariplus** [comment]
Okay, this is a bit tricky. I can modify the origins during runtime, but there's no way for me to know what the origin is, without the user entering it in the settings. It is usually the server address, but not always, such as in the case of SRV records. The best option is to add an input in the server settings for entering the Real IP of the MC server, which should always work.

**Comment by yariplus** [comment]
Looks like I can get the Real IP of the server using the mc plugin, this should avoid more manual setup. This does give me an idea though. The server settings page should really send out a test event when the user clicks save, and display if everything is kosher.

**Comment by yariplus** [comment]
Okay. The real solution is much dumber than I expected. All that is required is to change the header from 'origin' to 'referer', and it works perfectly fine with no changes to the NodeBB config needed.

**Comment by Electromaster232** [comment]
Also, make sure this gets merged so this issue can be closed @yariplus

**Comment by yariplus** [comment]
Fixed in latest jars.

https://github.com/yariplus/minecraft-nodebb-integration/releases/tag/v0.8.0-alpha.11
