### ISSUE TITLE
Update to 1.5

### ISSUE THREAD

**Issue by yariplus** [yariplus/nodebb-plugin-minecraft-integration#105]
Doesn't work mainly due to static asset changes in 1.5.

**Comment by phit** [comment]
I'm running 1.5.1 and it seems to work okay at least the server status widgets, I never really used anything else. 
Just some deprecation warnings `Use of the ".public" property is deprecated, use "visibility" now`.
Same for your featured Topic plugin btw.

**Comment by Electromaster232** [comment]
I guess you can close this now, as its being updated to 1.6 😄

**Comment by yariplus** [comment]
That is true.
