### ISSUE TITLE
Widgets not loading

### ISSUE THREAD

**Issue by da-van** [yariplus/nodebb-plugin-minecraft-integration#110]
None of the widgets are loading on any theme. NodeBB is connected to the MC server just fine and has all the info in debug log, but no widgets.

Console log

> nodebb-plugin-markdown-ext: loaded             main.js:4:1
> Loading Minecraft Integration...             client.js:8:2
> unreachable code after return statement [Learn More]             client.js:428:4
> 
> Source map error: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
> Resource URL: http://69.30.199.50:4567/assets/src/modules/sounds.js?v=qimh0i6966s
> Source Map URL: public/src/modules/sounds.js.map
> [Learn More]
> 
> Source map error: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
> Resource URL: http://69.30.199.50:4567/assets/src/client/chats/recent.js?v=qimh0i6966s
> Source Map URL: public/src/client/chats/recent.js.map
> [Learn More]
> 
> Source map error: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
> Resource URL: http://69.30.199.50:4567/assets/src/client/chats/search.js?v=qimh0i6966s
> Source Map URL: public/src/client/chats/search.js.map
> [Learn More]
> 
> Source map error: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
> Resource URL: http://69.30.199.50:4567/assets/src/client/chats/messages.js?v=qimh0i6966s
> Source Map URL: public/src/client/chats/messages.js.map
> [Learn More]
> 
> Source map error: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
> Resource URL: http://69.30.199.50:4567/assets/src/modules/scrollStop.js?v=qimh0i6966s
> Source Map URL: public/src/modules/scrollStop.js.map
> [Learn More]
> 
> Source map error: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
> Resource URL: http://69.30.199.50:4567/assets/src/modules/composer/drafts.js?v=qimh0i6966s
> Source Map URL: node_modules/nodebb-plugin-composer-default/static/lib/composer/drafts.js.map
> [Learn More]

**Comment by yariplus** [comment]
Hi there, is this crashing/freezing nodebb? or just refusing to render the widgets?

**Comment by PassTheMayo** [comment]
Yeah, same issue here. The widgets are like invisible, but I haven't checked logs yet.

**Comment by da-van** [comment]
@yariplus Doesn't freeze or crash nodebb. Whole board works fine, just the widgets don't show up.

**Comment by PassTheMayo** [comment]
@yariplus ^^^ Same here

**Comment by yariplus** [comment]
Widgets should load now.
