### ISSUE TITLE
Widgets not showing up

### ISSUE THREAD

**Issue by PassTheMayo** [yariplus/nodebb-plugin-minecraft-integration#111]
Hello! Thanks for making this plugin for NodeBB, it's ~~very helpful~~ would be helpful if it worked. I tried to install the plugin on the Minecraft server, and every time it would try to connect to the forum, it would say that it failed. Ended up using `"socket.io": { "origins": "*:*" }` to allow connections externally, and it worked. I then successfully enabled the key, but I am still getting problems. I enabled `/nodebb debug toggle`, and when it tries to send events to NodeBB itself, it gives me this:
```
[NodeBB-Integration] eventPlayerChat callback received with error: [[error:invalid-event]]
```
After that error, it said it successfully sent `eventStatus`, but the widget itself isn't appearing at all.

![image](https://user-images.githubusercontent.com/16949253/34510054-42ce6850-f016-11e7-96e2-c9b3c223b556.png)

![image](https://user-images.githubusercontent.com/16949253/34510064-4cd6d31e-f016-11e7-9748-dca6c882cd92.png)

It's like it doesn't even exist. I believe that I properly configured it, but I'm not sure what the issue is. Can anyone help?

**Comment by PassTheMayo** [comment]
Bigger issue that just happened to me: #109

**Comment by PassTheMayo** [comment]
Any more news on the problems? I'd like to have this on my forum, and this is currently the only plugin that can support NodeBB that has player count, etc.

**Comment by yariplus** [comment]
Still working on it.

**Comment by PassTheMayo** [comment]
Ok, thanks!
