### ISSUE TITLE
Completly crashed :c

### ISSUE THREAD

**Issue by ghost** [yariplus/nodebb-plugin-minecraft-integration#117]
Hey,
The plugins is just loading and loading on my forum but nothing is happend with it, just loading and loading .. hours over hours years over years but no god damn gui is opening.

**Comment by ghost** [comment]
https://i.gyazo.com/c45c017666762bb8060ce2c63ce3f167.png heres a image of my console

**Comment by ghost** [comment]
solved it myself 🤙

**Comment by yariplus** [comment]
Ok, lmk if you need help
