### ISSUE TITLE
How to setup the widgets?

### ISSUE THREAD

**Issue by ghost** [yariplus/nodebb-plugin-minecraft-integration#118]
Hey,
The example images aintaviable and there wanst a tutorial how to set the widgets up. Im a completly newbie to nodebb.

**Comment by yariplus** [comment]
Were you able to get the plugin to say it's connected in `/nodebb debug` ?

The widgets should be mostly self-explanatory once the plugin is connected.

**Comment by yariplus** [comment]
Update both plugins to v0.8.0-alpha.21 if you are having trouble.

https://github.com/yariplus/minecraft-nodebb-integration/releases/tag/v0.8.0-alpha.21

**Comment by ghost** [comment]
yea, thanks for youre unstable plugin .. maybe you will develop youre next one till stable before publishing ..

**Comment by yariplus** [comment]
Glad I could help man! Have a good one.
