### ISSUE TITLE
Disable Plugin Option

### ISSUE THREAD

**Issue by ASCIIcat** [yariplus/nodebb-plugin-minecraft-integration#40]
Perhaps add an option to disable the plugin list as not all servers want their plugin lists visible.

**Comment by yariplus** [comment]
Good point, I'll add this in.

But, just an FYI, I use the same query methods as vanilla, so if the widget is seeing your plugins, the plugin you have hiding the plugin list is not functioning correctly.

For example, Dinnerbone's Query Tool sees your plugins.
https://dinnerbone.com/minecraft/tools/status/
