### ISSUE TITLE
Minecraft widgets not showing up on v0.7.0

### ISSUE THREAD

**Issue by firelad97** [yariplus/nodebb-plugin-minecraft-integration#45]
Minecraft widgets do not show up on lastest master branch.

**Comment by yariplus** [comment]
For my plugin, are you running the npm version? (version 0.4.0) If you are on the master branch, it is unstable right now, try going back to 0.4.0.

Let me know if you are on 0.4.0 and it's still not working.

**Comment by yariplus** [comment]
Oh, I see what happened, I didn't update the npm version when I changed the name. Give me a few minutes.

**Comment by firelad97** [comment]
I should be running npm version. Actually I installed it via ACP. I'm new, so I don't know. If it's not npm version, I will delete it and install via npm.

**Comment by yariplus** [comment]
Np, you did it right, I'm fixing it now. Thanks for letting me know.

**Comment by yariplus** [comment]
Okay, I've updated the package to 0.4.1. It should be in the Installed Plugins page for you to update.

There are still some issues with the 2 "graph" widgets, so I disabled them. Working on a fix for them. I'll keep this issue open until that fix is ready.

**Comment by firelad97** [comment]
Does not detect your updated plugin, still says 0.4.0
EDIT: Nevermind, you have another plugin labeled intergration. It used to say 0.0.1 but now it says 0.4.1

**Comment by firelad97** [comment]
Still does not show up

**Comment by yariplus** [comment]
sorry give it few minutes

**Comment by yariplus** [comment]
Okay, it's there now for me.

**Comment by firelad97** [comment]
It's still not there. Probably because I just updated to v0.7.x branch.

**Comment by yariplus** [comment]
Strange. Have you run "npm up" from your NodeBB directory since you've updated?

If that still doesn't make it show up in the admin panel, just uninstall it and install it from the command line. Go to your NodeBB directory and do "npm install nodebb-plugin-minecraft-integration"

**Comment by firelad97** [comment]
No, it does show in ACP, just widgets that's not showing up on a page where I wanted it to be.

**Comment by yariplus** [comment]
Ah okay! I'll need more information then, which widgets, in which areas, and which theme you're using.

Also, is nodebb crashing or are there errors in your browser console?

Thanks!

**Comment by firelad97** [comment]
All widgets. Anywhere. Persona. No crashes. No errors.

**Comment by yariplus** [comment]
Thank you,

I did a fresh install here, still unable to reproduce.
http://52.0.45.41:4567/

Latest 0.7.x, Persona 0.1.55

There must be some other issue.

It's possible the plugin is not seeing your server, in this situation, it will make the widgets display nothing.

Turn on "Log Debug Messages" in the config page and run nobebb in dev mode `./nodebb dev`

It will spit a lot of data to the screen. Give it a few minutes to ping your server, then paste the data here.

**Comment by firelad97** [comment]
I'm using Openshift as my forum hosting. It works differently, so the log is always fixed. `./nodebb dev` does work, it restarted forum but gave me an error. Again, it's Openshift.

"Log Debug Messages" is already turned on.

**Comment by yariplus** [comment]
okay, what's the address of your Minecraft server? I'll test it in my instance to see if I can find any problems.

**Comment by firelad97** [comment]
mc.altimitmine.us (67.165.91.93)

**Comment by yariplus** [comment]
Yeah, I'm stuck, I tried it on two different boxes and it works fine.

I'm not very familiar with OpenShift. I'm not sure why it would be causing a problem, but it's definitely possible. Maybe for some reason it's blocking the incoming query connection.Just a guess.

**Comment by firelad97** [comment]
Alright, I will see and try to do something about that. Thanks.

**Comment by firelad97** [comment]
Finally, got `./nodebb dev` working. Here are the log: https://gist.github.com/Firelad97/0d10b64a99fb972d1519

**Comment by yariplus** [comment]
That part looks normal, after that shows up, it should wait ~1 minute then tell you it's pinging the server. Does that part ever come up?

**Comment by firelad97** [comment]
Yes, it did. Though Minecraft widgets aren't still showing up. Also, I have new issue with widgets, not just Minecraft. I can't stop dragging...

**Comment by yariplus** [comment]
If you disable minecraft widgets, do you still have that issue with regular widgets?.

**Comment by yariplus** [comment]
Try the new 0.5.0 version and report back.

Thanks.
