### ISSUE TITLE
Causing crash of nodebb

### ISSUE THREAD

**Issue by Fortifier42** [yariplus/nodebb-plugin-minecraft-integration#55]
```
9/9 10:47 [28234] - error: TypeError: Cannot read property 'name' of undefined
    at XXXX/nodebb/node_modules/nodebb-widget-minecraft-essentials/lib/updater.js:220:30
    at Object.asyncCallback [as callback] (dns.js:81:16)
    at Object.onresolve [as oncomplete] (dns.js:201:10)
TypeError: Cannot read property 'name' of undefined
    at XXXX/nodebb/node_modules/nodebb-widget-minecraft-essentials/lib/updater.js:220:30
    at Object.asyncCallback [as callback] (dns.js:81:16)
    at Object.onresolve [as oncomplete] (dns.js:201:10)
9/9 10:47 [28234] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
```

Crash on update of server parameters and on reload/restart of nodeBB

NodeBB v0.8.1
Plugin v0.5.2

**Comment by yariplus** [comment]
What is your server address?

**Comment by yariplus** [comment]
I need your server address so I can fix. I added a check so it won't crash if SRV doesn't return a 'name', but I can't guarantee that will solve the problem, just stop the crash.

**Comment by Fortifier42** [comment]
Sorry, I've been away since I posted this,

Minecraft server is located @ irc.theausfort.net (SRV record)
Forums are @ forum.theausfort.net

**Comment by yariplus** [comment]
Appears to be working for me on v0.5.6

![](http://puu.sh/kjdVO/aa8941e21c.png)

**Comment by Fortifier42** [comment]
Would seem that the "nodebb-widget-minecraft-essentials" plugin was the issue.

I'd recommend removing it from the repo if it isn't going to be maintained ;)

**Comment by yariplus** [comment]
D'oh. My fault. It's supposed to be just a mirror of this plugin, but I keep forgetting I have to push it separately.

**Comment by yariplus** [comment]
I updated the old repo and tagged it as depreciated. Thanks again for letting me know. :)
