### ISSUE TITLE
Option to display multiple prefixes

### ISSUE THREAD

**Issue by comfysquirrel** [yariplus/nodebb-plugin-minecraft-integration#72]
Can an option be added to show all the user's prefixes? if a player has multiple ranks at once on the server, it currently only shows the prefix on the forum from their most recently added rank.

**Comment by yariplus** [comment]
Working on it.

**Comment by yariplus** [comment]
Just need to do a bit more testing. Which chat and permissions plugin are you using to display the prefixes?

**Comment by yariplus** [comment]
Displays as

```
PrimaryGroupPrefix SecondaryGroupPrefix ..OtherGroupPrefixes.. PlayerPrefix
```

I'll add additional display options later, let me know if you have any preferences.

Or if this doesn't work for you lmk, I've only tested it with PEX.

**Comment by yariplus** [comment]
Opps, derpped and left in some testing code.

Use this release.
https://github.com/yariplus/bukkit-plugin-nodebb-integration/releases/tag/v0.7.0-beta.3

**Comment by comfysquirrel** [comment]
Ok, I'm using PEX and [MultiPrefix](https://www.spigotmc.org/resources/multiprefix.8139/). On the forum it sometimes shows a double prefix. (if it helps, MultiPrefix adds a variable called group_prefix for use in chat formatting) 
![screen shot 2016-02-18 at 3 05 43 am](https://cloud.githubusercontent.com/assets/6022168/13138414/c5a8a5c4-d5ec-11e5-9c19-f0e8b94b7dde.png)
![screen shot 2016-02-18 at 3 02 30 am](https://cloud.githubusercontent.com/assets/6022168/13138415/c5a90514-d5ec-11e5-8503-634976c4622b.png)
Also note that the prefixes other than the first one don't have the gray shadow behind the letters, so they're not as easy to read.

**Comment by yariplus** [comment]
Fixed the bad shadowing.

I setup MultiPrefix, I'm not getting that strange double prefix though.

**Comment by yariplus** [comment]
Hmm, could be that vault is grabbing the player's primary group prefix if a player prefix doesn't exist.

I'll add a containsValue check, that should fix it.

**Comment by yariplus** [comment]
bfc7a15

**Comment by yariplus** [comment]
Should be fixed now.

Note, it doesn't proactively update the prefix, the player has to sign onto the server first.

**Comment by comfysquirrel** [comment]
Awesome, it does work now. :) Although I've noticed the prefix changes don't seem to take effect until I restart nodebb. Should we open another issue for that?

**Comment by yariplus** [comment]
It should only require the player to sign onto the minecraft server and do a browser refresh.

Yeah, open a new issue if it doesn't work after that.

**Comment by comfysquirrel** [comment]
Confirmed, it updates instantly when a player signs onto the minecraft server.
