### ISSUE TITLE
Scoreboard Widgets

### ISSUE THREAD

**Issue by comfysquirrel** [yariplus/nodebb-plugin-minecraft-integration#76]
This widget could show the scores of a configurable number of top players, pulled from a specified minecraft scoreboard objective.

**Comment by yariplus** [comment]
Thanks. Been wanting to do this for a while. I'm not very familiar with the scoreboard system yet. But I'll definitely look at it more for the next minor release.

If you have any good examples of how this might look on the browser, that would help a ton. I'm also switching all charts to D3.js, so if you see any D3 demos that look nice for mc scoreboards that would be great too.

**Comment by comfysquirrel** [comment]
A stacked bar chart could work well for scoreboards! Or even a pie chart option.
I would love to see scores over time as well with stacked area charts or streamgraphs, although the scoreboard system doesn't record any timestamps.

**Comment by comfysquirrel** [comment]
You could take snapshots of the scores at configurable intervals to make a graph over time. (on second thought, a simple line graph with a line for each player might look better than a stacked area graph for changes over time, because a player's ranking would not always be the same).

**Comment by comfysquirrel** [comment]
Another graph that could be interesting is one that compares multiple scores - using stacked bars and color coding per player, for example.

**Comment by yariplus** [comment]
I think I can do snapshots. I'm using a separate storage for votes already, it should be a similar implementation.

**Comment by yariplus** [comment]
I'm back from the dead. Going to be adding this next.

**Comment by yariplus** [comment]
Scoreboard widget is added now. Only shows current values, but it does log history. Will add time chart on a later update.
