### ISSUE TITLE
Error Listing Registered Minecraft Users

### ISSUE THREAD

**Issue by popey456963** [yariplus/nodebb-plugin-minecraft-integration#88]
Possibly related to the released MCPC compatible version, which is the Jar I'm using for the plugin.  Upon registering, everything goes as expected:

Minecraft Server:

```
12:42:42 [INFO] Codefined issued server command: /register key-U07Zc=59F=0Ex4wW==Ryc8jPMJCno1qtbL58JuKpnsOcWF7OLT5KwbzNxZ=OmzFz
12:42:42 [INFO] [NodeBB-Integration] Sending commandRegister
12:42:42 [INFO] [NodeBB-Integration] commandRegister callback received without error.
12:42:42 [INFO] [NodeBB-Integration] Received commandRegister callback
```

Minecraft Client:
![](http://puu.sh/pZ1od/75cd83ec10.png)

_(Side Note: Unknown why it's asking me to use email and password to register with, upon attempting this is just says "find your key", assuming this is from an old version)_

NodeBB Server:

```
Got "/register" command from Minecraft server 0.
Player Codefined is attempting to register with player key m3ixql72VrVdWsqVPFkJRQTYCSCO2LmBRvYn2GKkP6MTSLm9jen3ZEUvsnRGB6yn
Set the Minecraft UUID for UID 1 to a3aa3260075c496e6a5217e3973d2a7e
```

However, from here, it goes downhill.  Upon refreshing the register page, the following is found on the NodeBB Server:

```
Fetching Name for a3aa3260075c496e6a5217e3973d2a7e
```

Suggesting it's found the correct UUID.  But on the client-side no users are found:

![](http://puu.sh/pZ1kJ/9d0bdb46d5.png)

Minecraft: Test Pack, Please Ignore (1.6.4)
NodeBB: v1.0.3
Config.yml:

``` yml
forum:
  url: http://sinisterheavens.com/
  name: Sinister Heavens
  apikey: <secretAPIKey>
socketio:
  address: http://sinisterheavens.com
```

Players.yml is empty.

**Comment by yariplus** [comment]
The 0.7.3 version of the forum plugin should fix basic registration.

**Comment by yariplus** [comment]
@popey456963 Any update on this?

**Comment by popey456963** [comment]
Apologies, I thought I had replied.  This does indeed appear to fix the problem, thank-you so much for your time.

:+1:
