### ISSUE TITLE
Not appearing in plugins menu?

### ISSUE THREAD

**Issue by ghostnegotiator** [yariplus/nodebb-plugin-minecraft-integration#91]
Installed the plugin today and it does not appear into my admin panel at the plugins menu.

I am using NodeJS Trough NVM (Node Version 0.10.4X)
NodeBB version 1.1.2

Hopefully it can be debugged 👍

**Comment by yariplus** [comment]
This is likely because I load jsdom without checking node version compatibility. I have removed jsdom for the upcoming release, so that should fix it.

I pushed a prerelease version `0.8.0-alpha.1` to npm. This should work for you for the most part, although some features will be missing or broken.

If that version still fails to load, post your nodebb logs, there should be an error in there.

**Comment by ghostnegotiator** [comment]
Heya,

Thanks for the quick reply it seems indeed to popup into the menu now, althought he 'addserver' button seems not to be able to add a server. And feature and the way it works looks awesome! ;)

Here is what the button says at the 'Inspect' function of Chrome:

```
<button id="mia-add-server" type="button" class="btn btn-success"><i class="fa fa-plus fa-fw"></i> add_server</button>
```

**Comment by ghostnegotiator** [comment]
Figured out what was going into to the logs...

Here is the output:

```
20/9 22:05 [5827] - warn: [plugins/load] File not found: /home/[REDACTED]/nodebb/node_modules/nodebb-plugin-minecraft-integration/public/src/client.js (Ignoring)
20/9 22:05 [5827] - warn: [plugins/load] File not found: /home/[REDACTED]/nodebb/node_modules/nodebb-plugin-minecraft-integration/public/src/admin.js (Ignoring)
20/9 22:05 [5827] - warn: [plugins/nodebb-plugin-minecraft-integration] Mapped path 'js => /home/[REDACTED]/nodebb/node_modules/nodebb-plugin-minecraft-integration/public/src' not found.
```

**Comment by yariplus** [comment]
Thanks. Pushed a new version.

**Comment by ghostnegotiator** [comment]
Seems to be working all fine now! Awesome!
